# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: CC0-1.0

# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# Fix linting errors reported by rules that emit fix information
fix: true

# MD013/line-length : Line length
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013: false
