# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: CC0-1.0

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.1.1
    hooks:
      - id: reuse-lint-file
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      # gitlint hook is run in the commit-msg stage, so it will not run by
      # default in CI or when running pre-commit run --all-files.
      # To manually trigger gitlint using pre-commit for your last commit
      # message, use the following command:
      # yamllint disable-line rule:line-length
      #     pre-commit run gitlint --hook-stage commit-msg --commit-msg-filename .git/COMMIT_EDITMSG
      - id: gitlint
      # There is an additional gitlint-ci hook that can be used in CI, but it
      # will only lint the latest commit. Since we want to lint all commits in
      # a PR, we run gitlint in a dedicated workflow instead of using this hook.
      # - id: gitlint-ci
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - --strict
