version = 1

[[annotations]]
path = ["CONTRIBUTING.md", "README.md", ".vscode/extensions.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Common Ground Electronics <https://cgnd.dev>"
SPDX-License-Identifier = "CC0-1.0"
